### ISSUE TITLE
Project Initiation Checklist - Grain & Fiber N study

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/hemp#53]
- Use the following checklist to ensure that everything needed to start a project has been planned for and accounted. 
- [x] Land request
- [x] UFarm
- [ ] Equipment request
- [ ] Fertilizer, herbicide, etc. purchased
- [ ] Seeds/ plant materials purchased
- [ ] Flags, paint, etc. purchased
- [ ] Plastic mulch purchased/raised beds/mounds
- [ ] Irrigation materials purchased/secured
- [ ] Miscellaneous, i.e., envelopes for seeds, bags for soil samples, etc. purchased
- [ ] Review weather patterns for weeks before and during deployment

**Comment by Danielcalza** [comment]
Reference Grain & Fiber N study - Project Preparation SOP Issue #55. @brymz @AjitWX

**Comment by Danielcalza** [comment]
Reference 2021 Hemp plantings - quick overview #73 for UFarm field sizes and Land requests.

**Comment by Danielcalza** [comment]
Updates to be logged on SOP: https://github.com/TREC-Agroecology/hemp/wiki/Grain-&-Fiber-N-study---2021-SOP
