### ISSUE TITLE
Project Initiation Checklist - Grain & Fiber Planting Date Trial

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/hemp#59]
- Use the following checklist to ensure that everything needed to start a project has been planned for and accounted. 
- [x] Land request
- [x] UFarm
- [x] Equipment request
- [ ] Fertilizer, herbicide, etc. purchased
- [ ] Seeds/ plant materials purchased
- [x] Flags, paint, etc. purchased
- [x] Plastic mulch purchased/raised beds/mounds
- [x] Irrigation materials purchased/secured
- [x] Miscellaneous, i.e., envelopes for seeds, bags for soil samples, etc. purchased
- [x] Review weather patterns for weeks before and during deployment

**Comment by Danielcalza** [comment]
Reference Grain & Fiber Planting Date Trial - Project Preparation SOP Issue #58. @brymz @AjitWX

**Comment by Danielcalza** [comment]
Note: Plan for Herbicide trial - in addition

**Comment by Danielcalza** [comment]
Reference 2021 Hemp plantings - quick overview #73 for UFarm field sizes and Land requests.

**Comment by Danielcalza** [comment]
Updates to be logged on SOP: https://github.com/TREC-Agroecology/hemp/wiki/Grain-&-Fiber-Planting-Date-Trial---2021-SOP
