### ISSUE TITLE
Project Initiation Checklist - Essential Oil P Study

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/hemp#61]
- Use the following checklist to ensure that everything needed to start a project has been planned for and accounted. 
- [x] Land request
- [x] UFarm
- [x] Equipment request
- [ ] Fertilizer, herbicide, etc. purchased
- [ ] Seeds/ plant materials purchased
- [x] Flags, paint, etc. purchased
- [x] Plastic mulch purchased/raised beds/mounds
- [ ] Irrigation materials purchased/secured
- [x] Miscellaneous, i.e., envelopes for seeds, bags for soil samples, etc. purchased
- [ ] Review weather patterns for weeks before and during deployment

**Comment by Danielcalza** [comment]
Reference Grain & Fiber P Study - Project Preparation SOP Issue #60. @brymz @AjitWX

**Comment by Danielcalza** [comment]
Reference 2021 Hemp plantings - quick overview #73 for UFarm field sizes and Land requests.

**Comment by Danielcalza** [comment]
Updates to be made on SOP: https://github.com/TREC-Agroecology/hemp/wiki/Grain-&-Fiber-P-Study---2021-SOP
