### ISSUE TITLE
Project Initiation Checklist - Invasion Risk Trial

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/hemp#63]
- Use the following checklist to ensure that everything needed to start a project has been planned for and accounted. 
- [ ] Land request
- [ ] UFarm
- [ ] Equipment request
- [ ] Fertilizer, herbicide, etc. purchased
- [ ] Seeds/ plant materials purchased
- [ ] Flags, paint, etc. purchased
- [ ] Plastic mulch purchased
- [ ] Irrigation materials purchased
- [ ] Miscellaneous, i.e., envelopes for seeds, bags for soil samples, etc. purchased
- [ ] Review weather patterns for weeks before and during deployment

**Comment by Danielcalza** [comment]
Closed - until further notice
