### ISSUE TITLE
Project Initiation Checklist - Herbicide Study

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/hemp#76]
- Use the following checklist to ensure that everything needed to start a project has been planned for and accounted. 
- [x] Land request
- [x] UFarm
- [x] Equipment request
- [x] Fertilizer, herbicide, etc. purchased
- [x] Seeds/ plant materials purchased
- [x] Flags, paint, etc. purchased
- [x] Plastic mulch purchased/raised beds/mounds
- [x] Irrigation materials purchased/secured
- [x] Miscellaneous, i.e., envelopes for seeds, bags for soil samples, etc. purchased
- [ ] Review weather patterns for weeks before and during deployment

**Comment by Danielcalza** [comment]
Updates to be made on SOP: https://github.com/TREC-Agroecology/hemp/wiki/Herbicide-Study---2021-SOP
