### ISSUE TITLE
Project Initiation Checklist - Essential Oil N Trial 2022

### ISSUE THREAD

**Issue by AjitWX** [TREC-Agroecology/hemp#86]
- Use the following checklist to ensure that everything needed to start a project has been planned for and accounted. 
- [x] Land request
- [x] UFarm
- [x] Equipment request
- [x] Fertilizer, herbicide, etc. purchased
- [x] Seeds/ plant materials purchased
- [x] Flags, paint, etc. purchased
- [x] Plastic mulch purchased/raised beds/mounds
- [x] Irrigation materials purchased/secured
- [x] Miscellaneous, i.e., envelopes for seeds, bags for soil samples, etc. purchased
- [ ] Review weather patterns for weeks before and during deployment
